### ISSUE TITLE
about scrollListener

### ISSUE THREAD

**Issue by junchenChow** [dinuscxj/PullZoomRecyclerView#4]
this view not addOnScrollListener and setOnScrollListener methods.
how to listener the PullZoomRecyclerView scroll to the bottom action.

**Comment by dinuscxj** [comment]
there are two methods: 
the first method

``` java
mRecyclerView.setModel(PullZoomBaseView.ZOOM_FOOTER);
mRecyclerView.setOnPullZoomListener(PullZoomBaseView.OnPullZoomListener);
```

you can also reference the link https://github.com/dinuscxj/PullZoomRecyclerView/blob/master/app/src/main/java/app/dinus/com/pullzoomrecyclerview/PullZoomFooterActivity.java
the second method

``` java
mRecyclerView.getRecyclerView().addOnScrollListener(RecyclerView.OnScrollListener);
```
