### ISSUE TITLE
每次进来第一次向下滑动会卡顿

### ISSUE THREAD

**Issue by codeQX** [dinuscxj/PullZoomRecyclerView#5]
第一次滑动的时候会卡顿

**Comment by dinuscxj** [comment]
@lucifill 我这里测试的不卡顿，你是不是首屏加载的item比较大啊？

**Comment by codeQX** [comment]
@dinuscxj 我是直接运行你的demo，PullZoomHeaderActivity第一次向下滑动，滑动一段距离之后header图片才会突然变大，重复操作后就很顺畅了，只是第一次滑动的时候会出现这种现象。

**Comment by dinuscxj** [comment]
@lucifill 修复了， 前一段时间merge pr的时候出错了 gradle dependency可能要晚些时间

**Comment by dinuscxj** [comment]
@lucifill 代码已经推倒jcenter 版本1.0.2

**Comment by codeQX** [comment]
@dinuscxj nice
